### PR TITLE
Scytale cipher added

### PR DESCRIPTION
**Pull request by LuminousLizard**
I wrote a algorithm for the [Scytale Cipher](https://en.wikipedia.org/wiki/Scytale) if you want to use it for your package. Maybe the algorithm can be written shorter/prettier because I'm a programming novice .... but it works.

LuminousLizard

### CODE REVIEW

**Comment by tigertv** [comment]
Hi, @LuminousLizard, thanks for the PR!
I think it would be useful, but it breaks down on Python 2.7. Yeah, I'm still supporting it.

**Comment by LuminousLizard** [comment]
>[...] but it breaks down on Python 2.7. [...]

I never worked with Python2 but I think it's because line 28 und 46 with `ceil(len(text) / key)` ?! 
In Python3 `ceil(16 / 5) = 4` <- the desired result
In Python2 `ceil(16 / 5) = 3`

**Comment by tigertv** [comment]
I get the following on Python 2.7:
```
ciphers/scytale.py", line 29, in __enc
    for block_count in range(0, ceil(len(text) / key)):
TypeError: range() integer end argument expected, got float.
```
Also then I execute the code
```python
from secretpy import Scytale, CryptMachine
from secretpy import alphabets


def encdec(machine, plaintext):
    print(plaintext)
    enc = machine.encrypt(plaintext)
    print(enc)
    print(machine.decrypt(enc))
    print("-------------------------------")


key = 4
cm = CryptMachine(Scytale(), key)
plaintext = "I am hurt very badly help".replace(' ', '').lower()
encdec(cm, plaintext)
```
I'm getting not the same result from wiki ("iryyatbhmvaehedlurlp"):
```
iamhurtverybadlyhelp
iueaharrdemtyllhvbyp
iamhurtverybadlyhelp
-------------------------------
```

**Comment by LuminousLizard** [comment]
> ciphers/scytale.py", line 29, in __enc
>     for block_count in range(0, ceil(len(text) / key)):
> TypeError: range() integer end argument expected, got float.

Because e.g.:
in python2 => "floor(16/5) = 3.0"
in python3 => "floor(16/5) = 3"

I added an explicit conversion to int to fix it. I tested it with python2.7 and python3.9 and it works.

**Comment by tigertv** [comment]
```
in python2 => "floor(16/5) = 3.0"
in python3 => "floor(16/5) = 3"
```
There is an operator `//`:
```
16 // 5 = 3
```

**Comment by LuminousLizard** [comment]
Contains mistakes

**Comment by tigertv** [comment]
@LuminousLizard, that's not a problem.
I suppose you can fix. I will add your code after that.

**Pull request closed without merging**
